---
title: "crude test with return in series"
author: "Krishna Patel"
---



# 1. Loading libraries
```{r}
setwd("G:/Laptop/Books and imp/Ahmedabad University/College Work/SEM 9/Econometrics/Project")

library(fBasics)
library(quantmod)
library(fUnitRoots)

```

# 2. Exploring the data
```{r}
crude_oil12 <- read.delim("G:/Laptop/Books and imp/Ahmedabad University/College Work/SEM 9/Econometrics/Project/crudeoil1.txt")

head(crude_oil12)
tail(crude_oil12)
```

```{r}
dim(crude_oil12)

crudeprice=crude_oil12[,2]
plot(crudeprice,type='l')
``` 

```{r}
return <- as.numeric(crude_oil12[,4])
basicStats(return)
head(return)
tail(return)
dim(return)
plot(return,type='l')
```

```{r}
acf(crude_oil12[,2])
```

```{r}
adfTest(crude_oil12[,2],lags=5,type='c')
adfTest(crude_oil12[,2],lags=5,type='nc')
adfTest(crude_oil12[,2],lags=5,type='ct')
```

```{r}
basicStats(crude_oil12[,2])
```


return=log(crude_oil12[,3]/crude_oil12[,2])
```{r}
basicStats(return)
```

```{r}
adfTest(return,lags=5,type='c')
adfTest(return,lags=5,type='nc')
adfTest(return,lags=5,type='ct')
```

```{r}
Box.test(return,lag=10,type='Ljung')
```



```{r}
m2=arima(return,order=c(5,0,0))
m2
```

```{r}
names(m2)
tsdiag(m2)
```

```{r}
r1=c(1,-m2$coef[1:5])
p1=polyroot(r1)
p1
```

```{r}
pre=predict(m2,4)
pre
```
